#cloud-config

package_update: true
package_upgrade: true

ssh_pwauth: false

users:
  - name: ansible
    groups: users, admin
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - "ssh-ed25519 REDACTED"