apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  chart:
    spec:
      chart: grafana
      version: 6.56.5
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  timeout: 10m0s
  interval: 1h0m0s
  # valuesFrom:
  #   - kind: Secret
  #     name: influx-secrets
  #     valuesKey: values.yaml
  values:
    adminUser: admin
    adminPassword: REDACTED_HASH
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
          # - name: Prometheus
          #   type: prometheus
          #   access: proxy
          #   orgId: 1
          #   url: http://monitoring-prometheus-server.monitoring.svc.cluster.local
          #   isDefault: true
          #   version: 1
          #   editable: true
          - name: Loki
            type: loki
            access: proxy
            orgId: 1
            url: http://loki-gateway.monitoring.svc.cluster.local
            isDefault: true
            version: 1
            editable: true

    # dashboards:
    #   default:
    #     node-exporter:
    #       gnetId: 1860
    #       revision: 1
    #       datasource: Prometheus
    #     nut-exporter:
    #       gnetId: 15406
    #       datasource: Prometheus
    persistence:
      enabled: true
      size: 5Gi
    grafana.ini:
      server:
        domain: grafana.fyp.domain.com
        root_url: "%(protocol)s://%(domain)s/grafana"
        serve_from_sub_path: true
    ingress:
      enabled: true
      ingressClassName: traefik
      hosts:
        - "grafana.fyp.domain.com"
      annotations: { traefik.ingress.kubernetes.io/redirect-entry-point: https }
      tls:
        - hosts: [grafana.fyp.domain.com]
    